name: Publish to Quay.io
on:
  workflow_dispatch: {}
jobs:
  publish:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64"
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_TEMP_USER }}
          password: ${{ secrets.QUAY_TEMP_TOKEN }}
      - name: Build
        run: |
          docker buildx create --name builder --use --bootstrap
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag ebpfcode/tracee-tester:latest .
          docker image push quay.io/ebpfcode/tracee-tester:latest
